server:
  port: ${PORT:8080}

info:
  app:
    name: OSRS Bingo
    description: OSRS Bingo Re-imagined
    java:
      version: 11

management:
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          UP: 200
          DOWN: 503
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

spring:
  application:
    name: OSRS Bingo

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME}${POSTGRES_CONNECTION_OPTIONS:}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE_SIZE:2}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: ${DB_SCHEMA_NAME}
    locations: classpath:/db/migration

logging:
  level:
    root: info

discord:
  token: ${DISCORD_TOKEN}
